version: "3"

services:
  phoenix:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app
    ports:
      - "4000:4000"
    platform: linux/amd64
    command: mix phx.server