version: '3.8'
services:
  frontend:
    build:
      context: ./timemanagerfront
      dockerfile: Dockerfile
    image: timemanager5.azurecr.io/timemanager_front
    ports:
      - "3001:8080"
    networks:
      - timemanager_miror_default      
    depends_on:
      - backend
    restart: always
  backend:
    build:
      context: ./timemanagerback
      dockerfile: Dockerfile
      image: timemanager5.azurecr.io/timemanager_back
    ports:
      - "4000:4000"
    networks:
      - timemanager_miror_default      
    environment:
      DATABASE_URL: "ecto://postgres:postgres@db:5432/postgres"
      POOL_SIZE: "10"
      SECRET_KEY_BASE: "NAUeCxlFPyiSbnLhqEH0Zszalm1b9Q3J3wW/JW5DFTDQLR6LuRMaGSQ1ZoRPfEJv"
      PHX_SERVER: "true"
    restart: always
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - timemanager_miror_default  
volumes:
  postgres_data:
networks:
  timemanager_miror_default:
    external : true