version: '3'
services:
  frontend:
    build:
      context: ./timemanagerfront
      dockerfile: Dockerfile
    ports:
      - 3001:8080
    depends_on:
      - backend
    restart: always
  backend:
    build:
      context: ./timemanagerback
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    environment:
      DATABASE_URL: ecto://postgres:postgres@db:5432/app_dev
    depends_on:
      - db
    restart: always
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres_data:
