version: '3.8'
services:
  frontend:
    build:
      context: ./timemanagerfront
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    depends_on:
      - backend
    restart: always
  backend:
    build:
      context: ./timemanagerback
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "ecto://postgres:Epitech1@timemanagerdb.postgres.database.azure.com:5432/timemanagerdb"
      POOL_SIZE: "10"
      SECRET_KEY_BASE: "NAUeCxlFPyiSbnLhqEH0Zszalm1b9Q3J3wW/JW5DFTDQLR6LuRMaGSQ1ZoRPfEJv"
      PHX_SERVER: "true"
    restart: always
