version: '3.8'
services:
  frontend:
    build:
      context: ./timemanagerfront
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    depends_on:
      - backend
    restart: always
  backend:
    build:
      context: ./timemanagerback
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      DATABASE_USERNAME: "postgres"
      DATABASE_PASSWORD: "Epitech1"
      DATABASE_NAME: "timemanager"
      DATABASE_HOST: "timemanagerprod.database.windows.net"
      DATABASE_PORT: "5432"
      DATABASE_POOL_SIZE: "10"
      DATABASE_SSL: "true"
      # Ajoutez d'autres variables d'environnement nécessaires ici
    restart: always
