name: prod_check

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  elixir_tests:
    name: Elixir Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y libncurses5
    - name: Set up Elixir
      uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21
      with:
        elixir-version: '1.15.2'
        otp-version: '24.0'
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: timemanagerback/deps
        key: ${{ runner.os }}-mix-${{ hashFiles('timemanagerback/**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: |
        cd timemanagerback
        mix deps.get
    - name: Run tests
      run: |
        cd timemanagerback
        mix test
      continue-on-error: true

  tu_back:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Setup Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.11.x
        otp-version: 23.x
    - name: Install Dependencies
      run: mix deps.get
    - name: Run Tests
      run: mix test
      continue-on-error: true

  back:
    runs-on: ubuntu-latest
    steps:
      # ... vos étapes pour le job back ...

  front:
    runs-on: ubuntu-latest
    steps:
      # ... vos étapes pour le job front ...
